---
title: "Quantitative Methods II R Supplement"
date: 2023-02-13
output: 
  html_document: 
    theme: yeti 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# detach all libraries

detachAllPackages <- function() {
  basic.packages <- c("package:stats", "package:graphics", "package:grDevices", "package:utils", "package:datasets", "package:methods", "package:base")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search()))==1, TRUE, FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list)>0)  for (package in package.list) detach(package,  character.only=TRUE)
}
detachAllPackages()

# function to load libraries

pkgTest <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[,  "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg,  dependencies = TRUE)
  sapply(pkg,  require,  character.only = TRUE)
}

# knitr

knitr::knit_hooks$set(output = function(x, options){
  if(!is.null(options$max_height)){
    paste('<pre style = "max-height:', options$max_height, '; float: left; width: 910px; overflow-y: auto;">', x, "</pre>", sep = "")
  }else{
    x
  }
  
})

# loading packages 

lapply(c("tidyverse"),pkgTest)
lapply(c("kableExtra"),pkgTest)
lapply(c("reactable"),pkgTest)
library(tidyverse)
library(kableExtra)
library(reactable)
```

```{css, echo=FALSE}
  #TOC {
    max-width: fit-content;
    white-space: nowrap;
  }
  
  div:has(> #TOC) {
    display: flex;
    flex-direction: row-reverse;
}
```

### Homework 5
**Due 02/14/23**

```{r, warning=FALSE}
# set working directory to where csv is saved beforehand
# setwd("/Users/carolinelee/Desktop/Baby Researchers/qm2/datasets")
# setwd("/Users/Elizabeth Bell/OneDrive - Southern Methodist University/Desktop/baby-researchers/qm2/datasets")
setwd("/Users/Elizabeth Bell/OneDrive - Southern Methodist University/Desktop/baby-researchers/qm2/datasets")

df <- read_csv("Race3Math.csv", show_col_types = FALSE)
```

```{r, results='asis'}
reactable(
  df, 
  filterable = TRUE,
  showPageSizeOptions = TRUE, 
  striped = TRUE, 
  highlight = TRUE,
  resizable = TRUE,
  theme = reactableTheme(
    color = "hsl(233, 9%, 87%)",
    backgroundColor = "hsl(233, 9%, 19%)",
    borderColor = "hsl(233, 9%, 22%)",
    stripedColor = "hsl(233, 12%, 22%)",
    highlightColor = "hsl(233, 12%, 24%)",
    inputStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
    selectStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
    pageButtonHoverStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
    pageButtonActiveStyle = list(backgroundColor = "hsl(233, 9%, 28%)")
  )
)
```


