---
title: "Quantitative Methods II R Supplement"
output: 
  html_document: 
    theme: yeti 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# detach all libraries

detachAllPackages <- function() {
  basic.packages <- c("package:stats", "package:graphics", "package:grDevices", "package:utils", "package:datasets", "package:methods", "package:base")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search()))==1, TRUE, FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list)>0)  for (package in package.list) detach(package,  character.only=TRUE)
}
detachAllPackages()

# function to load libraries

pkgTest <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[,  "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg,  dependencies = TRUE)
  sapply(pkg,  require,  character.only = TRUE)
}

knitr::knit_hooks$set(output = function(x, options){
  if(!is.null(options$max_height)){
    paste('<pre style = "max-height:', options$max_height, '; float: left; width: 910px; overflow-y: auto;">', x, "</pre>", sep = "")
  }else{
    x
  }
  
})

lapply(c("tidyverse"),pkgTest)
library(tidyverse)
```

```{css, echo=FALSE}
  #TOC {
    max-width: fit-content;
    white-space: nowrap;
  }
  
  div:has(> #TOC) {
    display: flex;
    flex-direction: row-reverse;
}
```
    
## Homework 2

```{r, warning=FALSE}
df_hw2 <- read.csv("https://raw.githubusercontent.com/carolinelee78/school-stuff/main/Spring-2023/HW2_Dataset.csv?token=GHSAT0AAAAAAB5NON4SLJOXVLCQXE7BEL2MY6UKF3A")

```

## Lecture 4  

**January 26th, 2023** 






